# Generated by Django 4.2.7 on 2024-06-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_rename_message_mail_alter_mail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_send_date', models.DateTimeField(verbose_name='Дата и время первой отправки')),
                ('frequency', models.CharField(choices=[('D', 'Ежедневно'), ('W', 'Еженедельно'), ('M', 'Ежемесячно')], default='D', max_length=2, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('C', 'Завершена'), ('CR', 'Создана'), ('R', 'Запущена')], default='CR', max_length=2, verbose_name='Статус рассылки')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mail', verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'mailing',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_date', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('S', 'Успешно'), ('F', 'Не успешно')], default='F', max_length=1, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'db_table': 'mailing_attempt',
            },
        ),
    ]
