# Generated by Django 4.2.7 on 2024-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_remove_mailing_first_send_date_mailing_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='first_send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первой отправки'),
        ),
    ]
