# Generated by Django 4.2.7 on 2024-06-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_mailingattempt_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_all_mailings', 'Может просматривать любые рассылки'), ('disable_mailings', 'Может отключать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
